/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'caption' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const MenuCategory = IDL.Variant({
  'thali' : IDL.Null,
  'shakes' : IDL.Null,
  'sandwich' : IDL.Null,
  'snacks' : IDL.Null,
  'beverages' : IDL.Null,
  'pizza' : IDL.Null,
  'burger' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'isRecommended' : IDL.Bool,
  'category' : MenuCategory,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalyticsView = IDL.Record({
  'totalMenuItems' : IDL.Nat,
  'totalGalleryImages' : IDL.Nat,
  'totalReviews' : IDL.Nat,
  'pageViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'approved' : IDL.Bool,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
});
export const CafeInfo = IDL.Record({
  'contactInfo' : IDL.Text,
  'isOpen' : IDL.Bool,
  'openingHours' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [IDL.Nat], []),
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'approveReview' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsView], ['query']),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getCafeInfo' : IDL.Func([], [IDL.Opt(CafeInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRecommendedMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getTopRatedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementPageView' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReview' : IDL.Func([Review], [IDL.Nat], []),
  'updateCafeInfo' : IDL.Func([CafeInfo], [], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'caption' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const MenuCategory = IDL.Variant({
    'thali' : IDL.Null,
    'shakes' : IDL.Null,
    'sandwich' : IDL.Null,
    'snacks' : IDL.Null,
    'beverages' : IDL.Null,
    'pizza' : IDL.Null,
    'burger' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'isRecommended' : IDL.Bool,
    'category' : MenuCategory,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalyticsView = IDL.Record({
    'totalMenuItems' : IDL.Nat,
    'totalGalleryImages' : IDL.Nat,
    'totalReviews' : IDL.Nat,
    'pageViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'approved' : IDL.Bool,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const CafeInfo = IDL.Record({
    'contactInfo' : IDL.Text,
    'isOpen' : IDL.Bool,
    'openingHours' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [IDL.Nat], []),
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'approveReview' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsView], ['query']),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getCafeInfo' : IDL.Func([], [IDL.Opt(CafeInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRecommendedMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getTopRatedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementPageView' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReview' : IDL.Func([Review], [IDL.Nat], []),
    'updateCafeInfo' : IDL.Func([CafeInfo], [], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, MenuItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };