/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsView {
  'totalMenuItems' : bigint,
  'totalGalleryImages' : bigint,
  'totalReviews' : bigint,
  'pageViews' : Array<[string, bigint]>,
}
export interface CafeInfo {
  'contactInfo' : string,
  'isOpen' : boolean,
  'openingHours' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : bigint,
  'caption' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export type MenuCategory = { 'thali' : null } |
  { 'shakes' : null } |
  { 'sandwich' : null } |
  { 'snacks' : null } |
  { 'beverages' : null } |
  { 'pizza' : null } |
  { 'burger' : null };
export interface MenuItem {
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'isRecommended' : boolean,
  'category' : MenuCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface Review {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'approved' : boolean,
  'timestamp' : bigint,
  'rating' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], bigint>,
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'approveReview' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryImage' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAnalytics' : ActorMethod<[], AnalyticsView>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCafeInfo' : ActorMethod<[], [] | [CafeInfo]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getRecommendedMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getTopRatedReviews' : ActorMethod<[], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementPageView' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitReview' : ActorMethod<[Review], bigint>,
  'updateCafeInfo' : ActorMethod<[CafeInfo], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];